### ISSUE TITLE
anchors not found

### ISSUE THREAD

**Issue by wd-hub** [val-iisc/pose_estimation#1]
Hi,
It's really a great work, I'm trying to run the code following the instructions from the "Data Creation Pipeline".
However, when I tried to generate dense keypoints for synthetic images, i.e. run "python make_dense_pointset_syn.py --class_name CLASS_NAME", it could not find anchors/*.txt in the ../data/synthetic_data directory.
How I can get the anchors files?
Thanks!

**Comment by BardOfCodes** [comment]
Hi!
Sorry for the delay.
Thanks for pointing this out. I will update the code to include link to `anchors.zip` file.
For now, you can download and use the zip files from this link:
[https://drive.google.com/open?id=1_UUmDrM-Bg5KMbHJS-qtiscIsYkWi1_a](https://drive.google.com/open?id=1_UUmDrM-Bg5KMbHJS-qtiscIsYkWi1_a)

**Comment by wd-hub** [comment]
Hi Aditya,
The anchors.zip works now! Thanks a lot.
When I tried to run the ucn code, it comes with error:

_I0309 16:42:15.264346  9207 solver.cpp:87] Creating training net from net file: ./nets/train_classifier.prototxt
[libprotobuf ERROR google/protobuf/text_format.cc:307] Error parsing text-format caffe.NetParameter: 1424:43: Message type "caffe.LayerParameter" has no field named "convolutional_spatial_transformer_param".
F0309 16:42:15.265074  9207 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: ./nets/train_classifier.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)_

Is it due to the version of caffe? or a modified caffe?

**Comment by BardOfCodes** [comment]
Hi,

This is an error due to having a Caffe version which does not have the
Spatial Transformer Layer.
You can get a Caffe version containing that from here:
http://cvgl.stanford.edu/projects/ucn/.
While we did convert it the model to Pytorch, we cannot release/share the
code due to the agreement signed for the above code.
The UCN Caffe code is patented by NEC-labs, and you would need to send them
a signed form for using their code.
You can find further instructions on the link above.

Feel free to ask in case you have any more questions regarding our work!

Regard,
Aditya Ganeshan

**Comment by BardOfCodes** [comment]
@wd-hub, I hope your issue has been resolved.

**Comment by wd-hub** [comment]
@BardOfCodes I'm trying to contact with the NEC-labs for the password, thanks for your information.

**Comment by yruoxi** [comment]
Hi, I also ran into this issue, and thanks for the anchor files, another question, how do I generate those anchor points if I want to test for some other classes. Is there a tool for generating that?
